PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX tree: <https://w3id.org/lemon-tree#>
PREFIX gold: <http://purl.org/linguistics/gold/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX toe: <http://oldenglishthesaurus.arts.gla.ac.uk/>

###############################################################################
# Delete any owl:sameAs statements between entries
###############################################################################

WITH <urn:toe:senses>
DELETE {
    ?s ?p ?o
}
USING <urn:toe:senses>
WHERE {
    VALUES ?p { owl:sameAs owl:sameAsPrevious }
    ?s ?p ?o .
}
